"""Add archived column archived to todos

Revision ID: 1aded95d420a
Revises: 8a8c06b65317
Create Date: 2024-10-08 02:50:21.863045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aded95d420a'
down_revision: Union[str, None] = '8a8c06b65317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'archived')
    # ### end Alembic commands ###
