"""Add tags to todos

Revision ID: bc6c2cedb8ee
Revises: a517f7b2b2ed
Create Date: 2024-11-28 02:45:13.170105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc6c2cedb8ee"
down_revision: Union[str, None] = "a517f7b2b2ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("tags", sa.String(), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "tags")
    # ### end Alembic commands ###
